import unicornhat as uh
from unicorn_chars import *
import time
import colorsys


def main():
    uh.clear()
    print_11(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_10(2, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_9(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_8(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_7(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_6(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_5(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_4(2, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_3(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_2(3, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)
    print_1(4, GREEN)
    uh.show()
    time.sleep(0.5)
    uh.clear()
    time.sleep(0.2)

if __name__ == '__main__':
    main()
